@port = 8000
@host = http://localhost:{{port}}
@resto = /api/resto
@user_id = 1

### Get all users
GET {{host}}{{resto}} HTTP/1.1

### Make user employee role
@role_var = waiter
POST {{host}}{{resto}}/roles/{{user_id}}/{{role_var}} HTTP/1.1

### Get single employee
GET {{host}}{{resto}}/roles/{{user_id}} HTTP/1.1

### List all tables
GET {{host}}{{resto}}/tables HTTP/1.1

### List tables by user_id
GET {{host}}{{resto}}/tables/{{user_id}} HTTP/1.1

### Create table
@table_number=3
POST {{host}}{{resto}}/tables HTTP/1.1
Content-Type: application/json

{
    "number": {{table_number}},
    "waiter_id": 1,
    "order_status_id": 1
}

